#!/bin/sh

for cmd in "$@"; do
  case $cmd in
    get_brightness)
      # Requires m1ddc (in Brew)
      /opt/homebrew/bin/m1ddc get luminance
      ;;
    brightness+)
      osascript -e 'tell application "System Events"
                      key code 113
                    end tell'
      ;;
    brightness-)
      osascript -e 'tell application "System Events"
                      key code 107
                    end tell'
      ;;
    lock_screen)
      osascript -e 'tell application "System Events" to keystroke "q" using {control down, command down}'
      ;;
    switch_screen_to_displayport)
      # brew install m1ddc
      /opt/homebrew/bin/m1ddc set input 15
      ;;
    switch_screen_to_hdmi)
      # brew install m1ddc
      /opt/homebrew/bin/m1ddc set input 17
      ;;
    switch_screen_to_thunderbolt)
      # brew install m1ddc
      /opt/homebrew/bin/m1ddc set input 27
      ;;
    increase_monitor_volume)
      # brew install m1ddc
      /opt/homebrew/bin/m1ddc chg volume 5
      ;;
    decrease_monitor_volume)
      # brew install m1ddc
      /opt/homebrew/bin/m1ddc chg volume -5
      ;;
    turn_on_dnd)
      if [ $(defaults read com.apple.controlcenter "NSStatusItem Visible FocusModes") == 1 ]; then
        osascript -e 'tell application "System Events" to keystroke "d" using {shift down, option down, command down}'
        echo "🙎‍♂️"
      else
        osascript -e 'tell application "System Events" to keystroke "d" using {shift down, option down, command down}'
        echo "🙅‍♂️"
      fi
      ;;
    get_dnd)
      # Checks menu bar for DND status, will lag when disable as icon does not dissapear immediately
      if [ $(defaults read com.apple.controlcenter "NSStatusItem Visible FocusModes") == 1 ]; then
        echo "🙅‍♂️"
      else
        echo "🙎‍♂️"
      fi
      ;;
    get_volume_level)
      osascript -e 'output volume of (get volume settings)'
      ;;
    volume+)
      osascript -e 'set volume output volume (output volume of (get volume settings) + 3.125)
                    output volume of (get volume settings)'
      ;;
    volume-)
      osascript -e 'set volume output volume (output volume of (get volume settings) - 3.125)
                    output volume of (get volume settings)'
      ;;
    mute)
      osascript -e 'if get output muted of (get volume settings) is false then
                      set volume with output muted
                    else
                      set volume without output muted
                    end if
                    get output muted of (get volume settings)'
      ;;
    get_mute_state)
      osascript -e 'get output muted of (get volume settings)'
      ;;
    switch_audio_to_speakers)
      # Uses a shortcut for SoundSource bound to keystroke
      osascript -e 'tell application "System Events" to keystroke "s" using {shift down, control down, option down, command down}'
      ;;
    switch_audio_to_headphones)
      # Uses a shortcut for SoundSource bound to keystroke
      osascript -e 'tell application "System Events" to keystroke "h" using {shift down, control down, option down, command down}'
      ;;
    playpause)
      osascript -e 'tell application "Shortcuts Events" to run shortcut "play_pause"'
      ;;
    previous_track)
      osascript -e 'tell application "Shortcuts Events" to run shortcut "skip_back"'
      ;;
    next_track)
      osascript -e 'tell application "Shortcuts Events" to run shortcut "skip_forward"'
      ;;
    deepvibes_radio)
      osascript -e 'tell application "Shortcuts Events" to run shortcut "Deepvibes Radio"'
      ;;
    radio_6_music)
      osascript -e 'tell application "Shortcuts Events" to run shortcut "Radio 6 Music"'
      ;;
    cliqhop)
      osascript -e 'tell application "Shortcuts Events" to run shortcut "Cliqhop"'
      ;;

  esac
done
